### PR TITLE
REVIEWED: Fix being able to add a scenario without a name.

### LINKED ISSUE #106: Empty scenario added when you click cancel
If you try a new scenario and click cancel when you're prompted for the name you create a new scenario with no name.

### PR DESCRIPTION
**Pull request by morsdyce**
Closes #106

### CODE REVIEW

File: lib/ui/components/scenario-list.js [hunk 1]
```diff
@@ -21,7 +21,9 @@ export class ScenarioList extends React.Component {
   _addScenario() {
     const name = prompt('Please enter scenario name');
 
-    API.addScenario(name);
```
Comment (borisd) [inline lib/ui/components/scenario-list.js]: Maybe add HTML5 validation on that input?

Comment (morsdyce) [inline lib/ui/components/scenario-list.js]: It's not an input so can't add html5 validation to it.

Comment (borisd) [inline lib/ui/components/scenario-list.js]: Doh :)
